---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "kuisathaverat"
    groups:
      github-actions:
        patterns:
          - "opentelemetry-*"

  - package-ecosystem: "composer"
    directory: "docs/demos/jaeger/docker-compose.yml"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "kuisathaverat"

  - package-ecosystem: "composer"
    directory: "tests/docker-compose.yml"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "kuisathaverat"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "kuisathaverat"
