---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry-*"

  - package-ecosystem: "composer"
    directory: "docs/demos/jaeger/docker-compose.yml"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"

  - package-ecosystem: "composer"
    directory: "tests/docker-compose.yml"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
