repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
        exclude: (.+.bat$|.+.ps1$|^target/)
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace

-   repo: https://github.com/detailyang/pre-commit-shell.git
    rev: master
    hooks:
    -   id: shell-lint
        name: "Shellscript: lint"
        stages: [commit]
        types: [shell]

-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.25.0
    hooks:
    -   id: yamllint
        name: "Yaml: lint"
        args: ['-c','.yamlint.yml']
        stages: [commit]
        types: [yaml]
        exclude: (^.pre-commit-config.yaml$|^.pre-commit-hooks.yaml$)

-   repo: https://github.com/elastic/apm-pipeline-library.git
    rev: current
    hooks:
    -   id: check-bash-syntax
    -   id: check-abstract-classes-and-trait   # TODO: this hook won't be needed once the CI migration is completed
    -   id: check-jsonslurper-class   # TODO: this hook won't be needed once the CI migration is completed
    -   id: check-unicode-non-breaking-spaces
    -   id: remove-unicode-non-breaking-spaces
    -   id: check-en-dashes
    -   id: remove-en-dashes

-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        args: ['--ignore-words-list','pullrequest,pullrequests']
